//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proywsevaluaedu
{
    using System;
    using System.Collections.Generic;
    
    public partial class cSeccion
    {
        public short cSecId { get; set; }
        public string cSecNombre { get; set; }
        public short cSecPonderacion { get; set; }
    }
}
