//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proywsevaluaedu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVALUACIONDCEntities : DbContext
    {
        public EVALUACIONDCEntities()
            : base("name=EVALUACIONDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cfgPeriodoEvaluacion> cfgPeriodoEvaluacion { get; set; }
        public virtual DbSet<cOpcionCalificacion> cOpcionesCalificacion { get; set; }
        public virtual DbSet<cPregunta> cPreguntas { get; set; }
        public virtual DbSet<cSeccion> cSecciones { get; set; }
        public virtual DbSet<mEvaluacion> mEvaluacion { get; set; }
        public virtual DbSet<rSeccionxOpcionCalifica> rSeccionxOpcionesCalifica { get; set; }
        public virtual DbSet<dEvaluacion> dEvaluacion { get; set; }
    }
}
