//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proywsevaluaedu
{
    using System;
    using System.Collections.Generic;
    
    public partial class mEvaluacion
    {
        public long mEvaId { get; set; }
        public System.DateTime mEvaFecha { get; set; }
        public int cfgPEId { get; set; }
        public string mEvaComentarios { get; set; }
    }
}
